[2022-06-26 14:42:33.524445] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData()
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:42:33.526010] [ERROR] [./Quant.py] 
[2022-06-26 14:43:34.988236] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData()
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:43:34.990239] [ERROR] [./Quant.py] 
[2022-06-26 14:45:16.212082] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:45:16.213011] [ERROR] [./Quant.py] 
[2022-06-26 14:45:35.376142] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:45:35.377078] [ERROR] [./Quant.py] 
[2022-06-26 14:46:18.364778] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:46:18.366774] [ERROR] [./Quant.py] 
[2022-06-26 14:46:24.710305] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:46:24.711216] [ERROR] [./Quant.py] 
[2022-06-26 14:48:24.004593] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:48:24.005656] [ERROR] [./Quant.py] 
[2022-06-26 14:48:56.649164] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:48:56.650513] [ERROR] [./Quant.py] 
[2022-06-26 14:49:01.058900] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:49:01.060283] [ERROR] [./Quant.py] 
[2022-06-26 14:50:30.673571] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py]     marketData = DownloadHandler().downloadData()
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:50:30.675686] [ERROR] [./Quant.py] 
[2022-06-26 14:52:09.287729] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData(self)
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:52:09.289027] [ERROR] [./Quant.py] 
[2022-06-26 14:52:38.681340] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData()
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:52:38.682134] [ERROR] [./Quant.py] 
[2022-06-26 14:52:47.367739] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData()
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:52:47.369028] [ERROR] [./Quant.py] 
[2022-06-26 14:54:52.627181] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in <module>
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py]   File "./Quant.py", line 30, in run
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py]     marketData = downloadHandler.downloadData()
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py] AttributeError: 'NoneType' object has no attribute 'downloadData'
[2022-06-26 14:54:52.628654] [ERROR] [./Quant.py] 
[2022-06-26 14:58:32.524214] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]   File "./Quant.py", line 70, in <module>
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]   File "./Quant.py", line 29, in run
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]     marketData = downloadData()
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]   File "./Quant.py", line 49, in downloadData
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py]     data = yf.download(tickers=SP100, group_by='ticker')
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py] NameError: name 'yf' is not defined
[2022-06-26 14:58:32.525348] [ERROR] [./Quant.py] 
[2022-06-26 14:58:52.306747] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:01:41.036439] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:16:20.034416] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]   File "./Quant.py", line 83, in <module>
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]   File "./Quant.py", line 73, in analyzeData
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py] TypeError: 'Timestamp' object is not subscriptable
[2022-06-26 15:16:30.222520] [ERROR] [./Quant.py] 
[2022-06-26 15:18:12.206235] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]   File "./Quant.py", line 83, in <module>
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]   File "./Quant.py", line 73, in analyzeData
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py] TypeError: 'Timestamp' object is not subscriptable
[2022-06-26 15:18:12.503080] [ERROR] [./Quant.py] 
[2022-06-26 15:18:19.514263] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]   File "./Quant.py", line 83, in <module>
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]   File "./Quant.py", line 73, in analyzeData
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py] TypeError: 'Timestamp' object is not subscriptable
[2022-06-26 15:18:19.777534] [ERROR] [./Quant.py] 
[2022-06-26 15:20:00.051149] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]   File "./Quant.py", line 84, in <module>
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]   File "./Quant.py", line 74, in analyzeData
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py] TypeError: string indices must be integers
[2022-06-26 15:20:00.303550] [ERROR] [./Quant.py] 
[2022-06-26 15:20:10.283448] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]   File "./Quant.py", line 85, in <module>
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]   File "./Quant.py", line 45, in run
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]     marketData = downloadData()
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]   File "./Quant.py", line 57, in downloadData
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py]     df.head(3)
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py] NameError: name 'df' is not defined
[2022-06-26 15:20:10.595557] [ERROR] [./Quant.py] 
[2022-06-26 15:20:17.983440] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]   File "./Quant.py", line 85, in <module>
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]   File "./Quant.py", line 75, in analyzeData
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py] TypeError: string indices must be integers
[2022-06-26 15:20:18.293223] [ERROR] [./Quant.py] 
[2022-06-26 15:20:45.454313] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]   File "./Quant.py", line 85, in <module>
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]   File "./Quant.py", line 46, in run
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]     analyzeData(marketData)
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]   File "./Quant.py", line 75, in analyzeData
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py]     df['ma20'] = df['Adj Close'].rolling(window=20).mean()
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py] TypeError: string indices must be integers
[2022-06-26 15:20:45.804657] [ERROR] [./Quant.py] 
[2022-06-26 15:21:19.960109] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:02.861196] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:13.797037] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:27.420088] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:40.452777] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:48.106977] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:22:56.278050] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:23:23.581518] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:23:39.318273] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:29:24.755792] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     return self._engine.get_loc(casted_key)
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] KeyError: 'bnh_returns'
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] 
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] The above exception was the direct cause of the following exception:
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] 
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "./Quant.py", line 108, in <module>
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "./Quant.py", line 47, in run
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "./Quant.py", line 101, in createSignal
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     ma20Data['strategy_returns'] = ma20Data['bnh_returns'] * (ma20Data['position'])
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     indexer = self.columns.get_loc(key)
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py]     raise KeyError(key) from err
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] KeyError: 'bnh_returns'
[2022-06-26 15:29:25.094833] [ERROR] [./Quant.py] 
[2022-06-26 15:29:46.346770] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:36:38.242242] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['Lower_Band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['Lower_Band']), 1, 0)
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:36:38.545514] [ERROR] [./Quant.py] 
[2022-06-26 15:37:12.287613] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['lower_band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['lower_band']), 1, 0)
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:37:12.654723] [ERROR] [./Quant.py] 
[2022-06-26 15:37:26.998415] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['lower_band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['lower_band']), 1, 0)
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:37:27.363844] [ERROR] [./Quant.py] 
[2022-06-26 15:38:29.515010] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:38:35.117536] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:39:22.510466] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['lower_band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['lower_band']), 1, 0)
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:39:22.964550] [ERROR] [./Quant.py] 
[2022-06-26 15:39:59.915998] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]     createSignal(ma20Data)
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['lower_band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['lower_band']), 1, 0)
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:40:00.242942] [ERROR] [./Quant.py] 
[2022-06-26 15:40:07.762794] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]   File "./Quant.py", line 107, in <module>
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]     createSignal(ma20DataNew)
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]   File "./Quant.py", line 80, in createSignal
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py]     (ma20Data['Adj Close'] < ma20Data['lower_band']) & (ma20Data['Adj Close'].shift(1) >= ma20Data['lower_band']), 1, 0)
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py] TypeError: 'NoneType' object is not subscriptable
[2022-06-26 15:40:08.066850] [ERROR] [./Quant.py] 
[2022-06-26 15:40:15.872031] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:40:46.607102] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:41:11.455986] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:42:02.745507] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]   File "./Quant.py", line 111, in <module>
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]     createSignal(ma20DataNew)
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]   File "./Quant.py", line 98, in createSignal
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py]     ma20Data[['bnh_returns','strategy_returns']] = df[['bnh_returns','strategy_returns']].cumsum()
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py] NameError: name 'df' is not defined
[2022-06-26 15:42:03.168706] [ERROR] [./Quant.py] 
[2022-06-26 15:42:19.707142] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]   File "./Quant.py", line 111, in <module>
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]     createSignal(ma20DataNew)
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]   File "./Quant.py", line 98, in createSignal
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py]     ma20Data[['Buy_Hold','strategy_returns']] = df[['bnh_returns','strategy_returns']].cumsum()
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py] NameError: name 'df' is not defined
[2022-06-26 15:42:20.069325] [ERROR] [./Quant.py] 
[2022-06-26 15:42:27.048538] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "./Quant.py", line 111, in <module>
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "./Quant.py", line 48, in run
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     createSignal(ma20DataNew)
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "./Quant.py", line 98, in createSignal
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     ma20Data[['Buy_Hold','strategy_returns']] = ma20Data[['bnh_returns','strategy_returns']].cumsum()
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3030, in __getitem__
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1266, in _get_listlike_indexer
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1308, in _validate_read_indexer
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py]     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py] KeyError: "None of [Index(['bnh_returns', 'strategy_returns'], dtype='object')] are in the [columns]"
[2022-06-26 15:42:27.409759] [ERROR] [./Quant.py] 
[2022-06-26 15:43:21.226520] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:47:26.750664] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:53:55.126029] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 15:57:41.053025] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:24:17.805415] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:24:32.624150] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:25:15.812834] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:26:15.265832] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     return self._engine.get_loc(casted_key)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] KeyError: 'ma20'
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] 
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] The above exception was the direct cause of the following exception:
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] 
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3826, in _set_item
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     loc = self._info_axis.get_loc(key)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py", line 2876, in get_loc
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     loc = self._get_level_indexer(key, level=0)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py", line 3158, in _get_level_indexer
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     idx = self._get_loc_single_level_index(level_index, key)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py", line 2809, in _get_loc_single_level_index
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     return level_index.get_loc(key)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     raise KeyError(key) from err
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] KeyError: 'ma20'
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] 
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] During handling of the above exception, another exception occurred:
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] 
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] Traceback (most recent call last):
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "./Quant.py", line 112, in <module>
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     quant.run()
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "./Quant.py", line 60, in run
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     ma20DataDict = analyzeData(marketDataDict)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "./Quant.py", line 72, in analyzeData
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     marketData['ma20'] = marketData['Adj Close'].rolling(window=20).mean()
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3163, in __setitem__
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     self._set_item(key, value)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3243, in _set_item
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     NDFrame._set_item(self, key, value)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3829, in _set_item
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     self._mgr.insert(len(self._info_axis), key, value)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1203, in insert
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 2742, in make_block
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     return klass(values, ndim=ndim, placement=placement)
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]   File "D:\Users\caiedward\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 142, in __init__
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py]     raise ValueError(
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] ValueError: Wrong number of items passed 101, placement implies 1
[2022-06-26 16:26:18.041926] [ERROR] [./Quant.py] 
[2022-06-26 16:36:17.346282] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:36:58.136541] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:38:05.842563] [INFO] [./Quant.py] Running Quant project...
[2022-06-26 16:38:29.686711] [INFO] [./Quant.py] Running Quant project...
